config/routes.rb
RottenMangoes::Application.routes.draw do

  get 'movies', to: 'movies#index'

  resources :movies do
    resources :reviews
  end

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]


  namespace :admin do
    resources :users
    get '/users/:id/impersonate' => 'users#switch_to_user', as: :impersonate
    get 'return-to-self' => 'users#switch_to_admin', as: :return_to_self
  end

  root to: 'movies#index'











end

app/models/movie.rb
class Movie < ActiveRecord::Base

  # scope :with_title, -> (title) { where("title LIKE ?", "%#{title}%") }
  # scope :with_director, -> (director) { where("director like ?", "%#{director}%") }
  # scope :under_x_min, -> (max_limit) { where("runtime_in_minutes < ?", max_limit) }
  # scope :over_x_min, -> (min_limit) { where("runtime_in_minutes >= ?", min_limit) }
  # scope :with_title_or_director, -> (term) { where("title LIKE ? OR director LIKE ?", "%#{term}%", "%#{term}%") }

  has_many :reviews

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :poster_image_url,
    presence: true

  validates :release_date,
    presence: true

  mount_uploader :poster_image_url, AvatarUploader

  def review_average
    (reviews.sum(:rating_out_of_ten)/reviews.size) unless (reviews.size == 0)
  end

  def self.search(search)
    if search
      Movie.where("title LIKE ?", "%#{search}%")
    else
      Movie.all
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  max_paginates_per 10

  has_many :reviews

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  mount_uploader :avatar, AvatarUploader

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :restrict_access, except: [:switch_to_admin]

  def index
    @users = User.order("firstname").page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end 

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "#{@user.firstname} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def switch_to_user
    session[:admin_id] = current_user.id
    session[:user_id] = params[:id]

    redirect_to movies_path
  end

  def switch_to_admin
    if session[:admin_id]   
      session[:user_id] = session[:admin_id]
      session[:admin_id] = nil
    end
    redirect_to admin_users_path
  end
  
protected

  def require_admin
    unless current_user.admin?
      flash[:error] = "You must be an administrator to access this section"
      redirect_to movies_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def restrict_non_admins
    unless admin_user?
      redirect_to root_path, notice: "You must be an admin to access those pages"
    end
  end 

   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin_user?
    @admin_user ||= User.find(session[:admin_id]) if session[:admin_id]
  end

  helper_method :admin_user?
  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    #@movies = Movie.all
    @movies = Movie.search(params[:title])
    
    # @movies = @movies.with_title_or_director(params[:term]) if params[:term].present?
    # @movies = @movies.with_title(params[:title]) if params[:title].present?
    # @movies = @movies.with_director(params[:director]) if params[:director].present?
    # @movies = @movies.under_x_min(90) if params[:duration] == "2"
    # @movies = @movies.over_x_min(90).under_x_min(120) if params[:duration] == "3"
    # @movies = @movies.over_x_min(120) if params[:duration] == "4"
    
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie
  before_filter :restrict_access

  def new
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully!"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Oh hey #{user.firstname}! We've seen you here before."
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "See you later alligator!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.welcome_email(@user).deliver
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome to Rotten Mangoes, #{@user.firstname}! We're excited that you decided to join us."
    else
      render :new
    end unless admin_user?
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="container">
  <%= form_for [:admin, @user] do |f| %>
    <% if @user.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      </div>
      <div class="container">
        <ul class="list-group">
          <% @user.errors.full_messages.each do |msg| %>
            <li class="list-item"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, placeholder: "E-mail Address", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname, placeholder: "First Name", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname, placeholder: "Last Name", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password, placeholder: "Password", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :admin_user %>
        <%= f.check_box :admin_user, :class => "checkbox" %>
      </div>
      <div><%= f.submit "Submit", :class => "btn btn-default" %></div>
    </div>
  </div>
  <% end %>

app/views/admin/users/edit.html.erb
<%= link_to "Back to all users", admin_users_path %><br/>

<h1> Edit <%= @user.full_name %>: </h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<%= link_to "Create a new user", new_admin_user_path %><br>
<%= link_to "Back to all movies", movies_path %>

<% @users.each do |user| %>
  
  <h2><%= user.full_name %></h2>
  <h3><%= user.email %></h3>
  <h4><%= user.admin_user? ? "Admin" : "User" %></h4>
  <%= link_to "Edit",  edit_admin_user_path(user) %> |
  <%= link_to "Delete", admin_user_path(user), method: :delete, data: {confirm: "You sure?"}, title: "Delete #{user.full_name}" %>
  <% unless current_user == user %>
    | <%= link_to "Impersonate",  admin_impersonate_path(user) %>
  <% end %>
  <hr>
<% end %>

app/views/admin/users/new.html.erb
<%= link_to "Back to all users", admin_users_path %><br/>

<h1> Create a new user: </h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="page-header">
    <h1>User Profile: <%= link_to @user.full_name, user_path(@user) %> (<%= link_to "edit", edit_admin_user_path(@user) %>, <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "Are you absolutely sure??" %>)</h1>
  </div>
</div>

<div class="container">
  <h3>First name: <%= @user.firstname %></h3>
  <h3>Last name: <%= @user.lastname %></h3>
  <h3>Email: <%= @user.email %></h3>
  <h3>Created at: <%= formatted_date(@user.created_at) %></h3>
  <h3>Updated at: <%= formatted_date(@user.updated_at) %></h3>
  <h3>Admin:
    <% if @user.admin? %>
      Yes
    <% else %>
      No
    <% end %>
  </h3>
  <hr>
</div>

<div class="container">
  <h3>Reviews posted by <%= @user.full_name %>:</h3>
  <div class="container">
    <% if !current_user.reviews.empty? %>
      <%= render partial: "reviews/review", collection: @user.reviews %>
    <% else %>
      <h4>This user hasn't posted any reviews.</h4>
    <% end %>
  </div>
</div>

<div class="container">
  <hr>
  <%= link_to "Back to all users", admin_users_path %><br/>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <hr>
    <small>
      <% if current_user %>
        Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
        <%= link_to "Access Admin Area", admin_users_path if current_user.admin_user? %>


      <% else %>
        <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
      <% end %>
      

      <% if admin_user? %>
        | Admin user signed in as <%= admin_user.full_name %> | <%= link_to "Switch back to admin", admin_return_to_self_path %>
      <% end %>
    </small>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="Page">
  
  <% flash.each do |key,value|%>
    <%= content_tag(:div,value, class: "strong") %>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
  </div>


</body>
</html>

app/views/movies/_form.html.erb
  <%= form_for @movie, multipart: true  do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <%= f.label "title" %><br>
        <%= f.text_field "title", placeholder: "Movie Title", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "release_date"%><br>
        <%= f.date_field "release_date", placeholder: "YYYY-MM-DD", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "director" %><br>
        <%= f.text_field "director", placeholder: "Director's Full Name", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "runtime_in_minutes" %><br>
        <%= f.number_field "runtime_in_minutes", placeholder: "Lenght of Movie in Minutes", :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "poster_image_url" %><br>
        <%= f.file_field :poster_image_url, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "description" %><br>
        <%= f.text_area "description", placeholder: "Tell us about the movie!", :class => "form-control" %>
      </div>
      <div class="form-group">
        <div >
        <%= f.submit "Submit", class:"btn btn-success"%> 
        </div>
      </div>
    </div>
  </div>
<% end %>


 

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1><strong>Rotten Mangoes</strong></h1>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>
<%= form_tag movies_path, method: :get do %>
  <p>
    <%= label_tag "Search for movies:"  %><br>
    <%= text_field_tag :title, params[:title], placeholder: "Title" %>
    <%= submit_tag  "Search",:name => nil , class:"btn btn-success" %>
    <%= text_field_tag :director, params[:director], placeholder: "Director" %>
    <%= submit_tag  "Search",:name => nil , class:"btn btn-primary" %>
    <%= select_tag :Duration, options_for_select(["Under 90", "Between 90-120", "Over 120"]) %>
    <%= submit_tag  "Search",:name => nil , class:"btn btn-info" %>
  </p>
<% end %>

<% @movies.each do |movie| %><br>
  <%= link_to image_tag(movie.poster_image_url.thumb), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %> | <%= movie.review_average %>/10</h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
  <hr>
<% end %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<table>
  <tr>
    <td>
      <%= link_to image_tag(@movie.poster_image_url.thumb), movie_path(@movie) %>
      <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
      <h3><%= @movie.release_date %></h3>
      <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
      <p><%= @movie.review_average %>/10</p>
      <p><%= @movie.description %></p>
    </td>
  </tr>
</table>
<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>